feat(txfees): added charge fees method
dymensionxyz/osmosis pull request #76
Opened 2024-10-31 17:55 UTC by keruch

Closes: https://github.com/dymensionxyz/dymension/issues/1246

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documation of area A by adding ....*

## Brief Changelog

*(for example:)*
 
  - *The metadata is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *Daemons retrieve the RPC data from the blob cache*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

2024-11-02 15:30 UTC, omritoptix requested changes
great work.
mostly product requirements which were unclear.

2024-11-02 15:30 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +func (k Keeper) ChargeFees(
2 things:
1. should be swapped before sending to beneficiary (i.e send it DYM)
3. shouldnt be burned

2024-11-02 15:30 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +		k.Logger(ctx).Error("Unknown fee token", "denom", takerFeeCoin.Denom, "error", err)
I blv this can happen. imagine the following:
1. create rollapp without IRO
2. no pool exists
3. send ibc transfer an charge bridging fee

2024-11-02 15:30 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +		err = k.bankKeeper.BurnCoins(ctx, types.ModuleName, sdk.NewCoins(takerFeeCoin))
we shouldn't burn unknown fee tokens but send them to the community pool.
expanded more about that on later comment.

2024-11-02 15:30 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +		err = k.bankKeeper.BurnCoins(ctx, types.ModuleName, sdk.NewCoins(takerFeeCoin))
same here. shouldn't burn them but send them to the community pool.

2024-11-02 15:30 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +	err := k.bankKeeper.SendCoinsFromAccountToModule(ctx, payer, types.ModuleName, sdk.NewCoins(takerFeeCoin))
It's not clear on the PRD but the intent was to send tokens after swapping to DYM.
since currently we only give the owner fees on:
1. IRO (he gets dym directly cause taker fee is only in DYM)
2. SWAP (we assume at max 1 hop)

than we should always have a way to swap it for the beneficiary.

2024-11-03 19:11 UTC, mtsitrin commented on x/txfees/keeper/hooks.go
>  	}
do we need still need the epochs?

2024-11-03 19:26 UTC, mtsitrin commented
what about `feedecorator.go`? needs to be changed as well to support immediate swaps for gas fees

2024-11-03 19:34 UTC, mtsitrin commented on x/txfees/keeper/fees.go
> +		// Fee is unknown token, thus sent to the community pool
might be clearer to call `FundCommunityPool` here

2024-11-03 19:34 UTC, mtsitrin commented on x/txfees/keeper/fees.go
> +		k.Logger(ctx).Error("Failed to swap fee token to base token. Trying to burn the tokens", "denom", takerFeeCoin.Denom, "error", err)
wrong logging

2024-11-04 07:01 UTC, mtsitrin commented
@omritoptix maybe we can move the txfees module to dymension repo on this opportunity?

2024-11-04 11:45 UTC, keruch commented
we discusses not to handle non-DYM fees for now
https://github.com/dymensionxyz/dymension/issues/1387

2024-11-04 11:46 UTC, keruch commented on x/txfees/keeper/hooks.go
>  	}
yes we do! eg for non-DYM fees.

2024-11-04 11:50 UTC, omritoptix commented
@mtsitrin lets see if will have time for it. I'd rather not do it now.  opened an issue: https://github.com/dymensionxyz/dymension/issues/1388

2024-11-04 12:28 UTC, omritoptix approved these changes

2024-11-04 12:28 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +// If the fee token is unknown, it is burned directly.
```suggestion
// If the fee token is unknown, it is sent to the community pool.
```

2024-11-04 12:28 UTC, omritoptix commented on x/txfees/keeper/fees.go
> +	// If the fee token is unknown or the swap is unsuccessful, send the fee to the community pool
```suggestion
	// If the fee token is unknown or the swap is unsuccessful, emit event and return 
```

2024-11-04 15:10 UTC, merged